name: metricbeat

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: elasticsearch
  hosts: [ https://elasticsearch:9200 ]
  username: monitoring_internal
  password: ${MONITORING_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: [ /usr/share/metricbeat/ca.crt ]
  xpack.enabled: true
  period: 10s
  enabled: true
- module: logstash
  hosts: [ http://logstash:9600 ]
  xpack.enabled: true
  period: 10s
  enabled: true
- module: kibana
  hosts: [ https://kibana:5601 ]
  username: monitoring_internal
  password: ${MONITORING_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: [ /usr/share/metricbeat/ca.crt ]
  xpack.enabled: true
  period: 10s
  enabled: true
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: [ unix:///var/run/docker.sock ]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}
    ssl:
      certificate_authorities: [ /usr/share/metricbeat/ca.crt ]

output.elasticsearch:
  hosts: [ https://elasticsearch:9200 ]
  username: metricbeat_internal
  password: ${METRICBEAT_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: [ /usr/share/metricbeat/ca.crt ]

http:
  enabled: true
  host: 0.0.0.0
