name: heartbeat

heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - https://elasticsearch:9200
  username: heartbeat_internal
  password: ${HEARTBEAT_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: [ /usr/share/heartbeat/ca.crt ]

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch

processors:
- add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}
    ssl:
      certificate_authorities: [ /usr/share/heartbeat/ca.crt ]

output.elasticsearch:
  hosts: [ https://elasticsearch:9200 ]
  username: heartbeat_internal
  password: ${HEARTBEAT_INTERNAL_PASSWORD}
  ssl:
    certificate_authorities: [ /usr/share/heartbeat/ca.crt ]

http:
  enabled: true
  host: 0.0.0.0
